[project]
name = "seeder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "faker>=38.2.0",
    "passlib[bcrypt]>=1.7.4",
    "rich>=14.2.0",
    "sqlalchemy>=2.0.44",
]
