[project]
name = "auth-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["faststream[nats]>=0.6.3", "redis>=7.1.0"]

[tool.ruff]
line-length = 72
pydocstyle.convention = "google"
