[project]
name = "shared-messages"
version = "0.6.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["pydantic>=2.12.4"]

[dependency-groups]
dev = [
    "ruff>=0.14.7",
]
